department = '{:<30}'.format( input('학과 입력 : ') )
name =  '{:<30}'.format( input('이름 입력 : ') )
num1 = '{:=+30d}'.format( int(input('정수입력 : ')) )
num2 = '{:=+30d}'.format( int(input('정수입력 : ')) )
num3 = '{:=+30.3f}'.format( float(input('실수입력 : ')) )
num4 = '{:=+30.3f}'.format( float(input('실수입력 : ')) )

print('*'*30)
print(department)
print(name)
print(num1)
print(num2)
print(num3)
print(num4)
print('*'*30)
